#armin:
    # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  a1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: a1_joint
    pid: {p: 7000.0, i: 10000.01, d: 10.0}
  a2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: a2_joint
    pid: {p: 7000.0, i: 10000.01, d: 10.0}
  a3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: a3_joint
    pid: {p: 7000.0, i: 10000.01, d: 10.0}
  a4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: a4_joint
    pid: {p: 7000.0, i: 10000.01, d: 10.0}
  a5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: a5_joint
    pid: {p: 7000.0, i: 1000.01, d: 10.0}
  a6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: a6_joint
    pid: {p: 100.0, i: 1000.01, d: 10.0}
  armin:
   controller:
    position:
  #manipulator_controller:
     type: "position_controllers/JointTrajectoryController"
     joints:
      - a1_joint
      - a2_joint
      - a3_joint
      - a4_joint
      - a5_joint
      - a6_joint

     gains: # Required because we're controlling an effort interface
      a1_joint: {p: 700,  d: 0, i: 10000, i_clamp: 1}
      a2_joint: {p: 500,  d: 0, i: 10000, i_clamp: 1}
      a3_joint: {p: 500,  d: 0, i: 10000, i_clamp: 1}
      a4_joint: {p: 700,  d: 0, i: 10000, i_clamp: 1}
      a5_joint: {p: 700,  d: 0, i: 10000, i_clamp: 1}
      a6_joint: {p: 700,  d: 0, i: 10000, i_clamp: 1}
  #gazebo_ros_control:
  #  pid_gains:
  #      a1_joint: {p: 7000000,  d: 0, i: 10000}
  #      a2_joint: {p: 7000000,  d: 0, i: 10000}
  #      a3_joint: {p: 7000000,  d: 0, i: 10000}
  #      a4_joint: {p: 7000000,  d: 0, i: 10000}
  #      a5_joint: {p: 7000000,  d: 0, i: 10000}
  #      a6_joint: {p: 7000000,  d: 0, i: 10000}
