controller_list:
  - name: fake_manipulator_controller
    joints:
      - a1_joint
      - a2_joint
      - a3_joint
      - a4_joint
      - a5_joint
      - a6_joint
  - name: fake_base_controller
    joints:
      - a1_joint
      - a2_joint
      - a3_joint
      - a4_joint
      - a5_joint
      - a6_joint
  - name: fake_grip_controller
    joints:
      []
  - name: fake_a1_joint_group_controller
    joints:
      - a1_joint
  - name: fake_a2_joint_group_controller
    joints:
      - a2_joint
  - name: fake_a3_joint_group_controller
    joints:
      - a3_joint
  - name: fake_a4_joint_group_controller
    joints:
      - a4_joint
  - name: fake_a5_joint_group_controller
    joints:
      - a5_joint
  - name: fake_a6_joint_group_controller
    joints:
      - a6_joint