joint_limits:
  a1_joint:
    has_position_limits: true
    min_position: -6.28
    max_position: 6.28
    has_velocity_limits: true
    max_velocity: 0.410
    has_acceleration_limits: true
    max_acceleration: 0.010
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0
  a2_joint:
    has_position_limits: true
    min_position: -3.1415
    max_position: 3.1415
    has_velocity_limits: true
    max_velocity: 0.410
    has_acceleration_limits: true
    max_acceleration: 0.010
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0
  a3_joint:
    has_position_limits: true
    min_position: -3.1415
    max_position: 3.1415
    has_velocity_limits: true
    max_velocity: 0.410
    has_acceleration_limits: true
    max_acceleration: 0.010
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0
  a4_joint:
    has_position_limits: true
    min_position: -3.1415
    max_position: 3.1415
    has_velocity_limits: true
    max_velocity: 0.54
    has_acceleration_limits: true
    max_acceleration: 0.0134
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0
  a5_joint:
    has_position_limits: true
    min_position: -3.1415
    max_position: 3.1415
    has_velocity_limits: true
    max_velocity: 0.54
    has_acceleration_limits: true
    max_acceleration: 0.0134
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0
  a6_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 0.72 
    has_acceleration_limits: true
    max_acceleration: 0.018
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0
